[project]
name = "simplefst"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.setuptools_scm]

[tool.setuptools.packages]
find = { where = ["simplefst"] }

[build-system]
requires = ["setuptools", "setuptools-rust", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[[tool.setuptools-rust.ext-modules]]
target = "simplefst._lib"
path = "rust/Cargo.toml"
binding = "PyO3"
