[project]
name = "simplefst"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.setuptools_scm]

[tool.setuptools.packages]
find = { where = ["simplefst"] }

[build-system]
requires = ["setuptools", "setuptools-rust", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[[tool.setuptools-rust.ext-modules]]
target = "_fst"
path = "rust/Cargo.toml"
binding = "PyO3"

[tool.cibuildwheel]
environment = "PIP_ONLY_BINARY=:all:"
skip = "*_i686 pp* *musllinux* cp{31[!01],3[!01]?,[!3]*}-win32"
build-verbosity = 1
#test-requires = "pytest>=5.3.2 numpy Pillow>=7.0.0"
#test-command = "pytest {project}/test -vv"
